import { create } from 'xmlbuilder2';
import { Serie } from './a5_types'

// CRUD.serie.read({"tipo":"raster"},{include_geom:true}).then(r=>series=r)

function seriesToGmd(series : Serie[]) {
    var xml = create({ version: '1.0', encoding: 'UTF-8' })
    for(var serie of series) { 
        xml = append_MD_Element(xml, serie)
    }
    return xml.end({ prettyPrint: true });
}

function serieToGmd(serie : Serie) : string {    
    // Create XML structure
    var xml = create({ version: '1.0', encoding: 'UTF-8' })
    xml = append_MD_Element(xml, serie)
    return xml.end({ prettyPrint: true });
}

function append_MD_Element(xml, serie : Serie) {
    return xml
        .ele('gmd:MI_Metadata', { 'xmlns:gmd': 'http://www.isotc211.org/2005/gmd', 'xmlns:gco': 'http://www.isotc211.org/2005/gco', 'xmlns:gml': 'http://www.opengis.net/gml/3.2', "xmlns:gmi": "http://www.isotc211.org/2005/gmi", 'xmlns:xsi': "http://www.w3.org/2001/XMLSchema-instance", 'xsi:schemaLocation': "https://www.isotc211.org/2005/gmd gmd.xsd"})
                .ele('gmd:fileIdentifier')
                .ele('gco:CharacterString').txt(serie.id.toString()).up()
            .up()
            .ele('gmd:language')
                .ele('gco:CharacterString').txt('es').up()
            .up()
            .ele('gmd:characterSet')
                .ele('gmd:MD_CharacterSetCode', { codeListValue: 'utf8', codeList: 'http://www.ngdc.noaa.gov/metadata/published/xsd/schema/resources/Codelist/gmxCodelists.xml#MD_CharacterSetCode' }).txt('utf8').up()
            .up()
            .ele('gmd:hierarchyLevel')
                .ele('gmd:MD_ScopeCode', { codeListValue: 'series', codeList: 'http://www.ngdc.noaa.gov/metadata/published/xsd/schema/resources/Codelist/gmxCodelists.xml#MX_ScopeCode' }).txt('series').up()
            .up()
            .ele('gmd:contact')
                .ele('gmd:CI_ResponsibleParty')
                    .ele('gmd:organisationName')
                        .ele('gco:CharacterString').txt('Instituto Nacional del Agua').up()
                    .up()
                    .ele('gmd:role')
                        .ele('gmd:CI_RoleCode', { codeListValue: 'author', codeList: 'http://www.ngdc.noaa.gov/metadata/published/xsd/schema/resources/Codelist/gmxCodelists.xml#CI_RoleCode' }).txt('author').up()
                    .up()
                .up()
            .up()
            .ele('gmd:contact')
                .ele('gmd:CI_ResponsibleParty')
                    .ele('gmd:organisationName')
                        .ele('gco:CharacterString').txt(serie.fuente.source || serie.fuente.nombre || 'Unknown').up()
                    .up()
                    .ele('gmd:role')
                        .ele('gmd:CI_RoleCode', { codeListValue: 'originator', codeList: 'http://www.ngdc.noaa.gov/metadata/published/xsd/schema/resources/Codelist/gmxCodelists.xml#CI_RoleCode' }).txt('originator').up()
                    .up()
                .up()
            .up()
            .ele('gmd:dateStamp')
                .ele('gco:DateTime').txt(new Date().toISOString()).up()
            .up()
            .ele('gmd:identificationInfo')
                .ele('gmd:MD_DataIdentification')
                    .ele('gmd:abstract')
                        .ele('gco:CharacterString').txt(serie.fuente.abstract || 'N/A').up()
                    .up()
                    .ele('gmd:topicCategory')
                        .ele('gmd:MD_TopicCategoryCode').txt(serie.var.GeneralCategory || 'Unknown').up()
                    .up()
                    .ele('gmd:extent')
                        .ele('gmd:EX_Extent')
                            .ele('gmd:geographicElement')
                                .ele('gmd:EX_GeographicBoundingBox')
                                    .ele('gmd:westBoundLongitude')
                                        .ele('gco:Decimal').txt(serie.estacion.geom.coordinates[0][0][0]).up()
                                    .up()
                                    .ele('gmd:eastBoundLongitude')
                                        .ele('gco:Decimal').txt(serie.estacion.geom.coordinates[0][1][0]).up()
                                    .up()
                                    .ele('gmd:southBoundLatitude')
                                        .ele('gco:Decimal').txt(serie.estacion.geom.coordinates[0][2][1]).up()
                                    .up()
                                    .ele('gmd:northBoundLatitude')
                                        .ele('gco:Decimal').txt(serie.estacion.geom.coordinates[0][0][1]).up()
                                .up()
                            .up()
                        .up()
                    .up()
                    .ele('gmd:temporalExtent')
                        .ele('gmd:EX_TemporalExtent')
                            .ele('gmd:extent')
                                .ele('gml:TimePeriod')
                                    .ele('gml:beginPosition').txt(serie.date_range.timestart instanceof Date ? serie.date_range.timestart.toISOString() : serie.date_range.timestart || 'N/A').up()
                                    .ele('gml:endPosition').txt(serie.date_range.timeend instanceof Date ? serie.date_range.timeend.toISOString() : serie.date_range.timeend || 'N/A').up()
                                .up()
                            .up()
                        .up()
                    .up()
                    .ele('gmd:keyword')
                        .ele('gmd:MD_Keywords')
                            .ele('gmd:keyword')
                                .ele('gco:CharacterString').txt(serie.var.VariableName || 'N/A').up()
                            .up()
                        .up()
                    .up()
                    .ele('gmd:keyword')
                        .ele('gmd:MD_Keywords')
                            .ele('gmd:keyword')
                                .ele('gco:CharacterString').txt(serie.estacion.nombre || 'N/A').up()
                            .up()
                        .up()
                    .up()
                    .ele('gmd:keyword')
                        .ele('gmd:MD_Keywords')
                            .ele('gmd:keyword')
                                .ele('gco:CharacterString').txt(serie.procedimiento.nombre || 'N/A').up()
                            .up()
                        .up()
                    .up()
                    .ele('gmd:keyword')
                        .ele('gmd:MD_Keywords')
                            .ele('gmd:keyword')
                                .ele('gco:CharacterString').txt(serie.unidades.abrev || 'N/A').up()
                            .up()
                        .up()
                    .up()
                .up()
            .up()
            .ele('gmd:distributionInfo')
                .ele('gmd:MD_Distribution')
                    .ele('gmd:transferOptions')
                        .ele('gmd:MD_DigitalTransferOptions')
                            .ele('gmd:onLine')
                                .ele('gmd:CI_OnlineResource')
                                    .ele('gmd:linkage')
                                        .ele('gmd:URL').txt(`https://alerta.ina.gob.ar/a5/obs/${serie.tipo}/series/${serie.id}?include_geom=true&format=geojson`).up()
                                    .up()
                                .up()
                            .up()
                        .up()
                    .up()
                .up()
            .up()
        .up();
}

module.exports = {
    serieToGmd: serieToGmd,
    seriesToGmd: seriesToGmd
}
